import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)

test('UI actions use theme-safe semantic tokens', async () => {
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  const importer = await readFile(new URL('src/ui/CCSwitchImportSection.mjs', root), 'utf8')
  assert.match(styles, /--dsw-alias-button-primary-fill/)
  assert.match(styles, /--dsw-alias-label-primary-foreground/)
  assert.match(styles, /--dsw-alias-button-primary-hover/)
  assert.doesNotMatch(styles, /background:var\(--dsw-alias-surface-primary,#fff\)/)
  assert.match(importer, /dsh-ccswitch-import__primary/)
  assert.match(importer, /dsh-ccswitch-import__secondary/)
})

test('reasoning editor exposes compact list and collapsed wire mapping hooks', async () => {
  const ui = await readFile(new URL('src/ui/ReasoningSettingsSection.mjs', root), 'utf8')
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  assert.match(ui, /dsh-reasoning-model__identity/)
  assert.match(ui, /dsh-reasoning-mode/)
  assert.match(ui, /自定义 wire 值/)
  assert.match(ui, /dsh-reasoning-custom/)
  assert.match(styles, /dsh-reasoning-mode/)
  assert.match(styles, /dsh-reasoning-custom/)
})

test('reasoning editor separates mode, effort, advanced, and save hierarchy', async () => {
  const ui = await readFile(new URL('src/ui/ReasoningSettingsSection.mjs', root), 'utf8')
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  assert.match(ui, /dsh-reasoning-model__header/)
  assert.match(ui, /dsh-reasoning-model__mode-area/)
  assert.match(ui, /dsh-reasoning-model__body/)
  assert.match(ui, /dsh-reasoning-model__footer/)
  assert.match(ui, /dsh-reasoning-levels__heading/)
  assert.match(ui, /dsh-reasoning-levels__options/)
  assert.match(ui, /dsh-reasoning-levels__summary/)
  assert.match(ui, /selectedCount/)
  assert.match(ui, /已选/)
  assert.match(ui, /dsh-reasoning-custom__toggle--active/)
  assert.match(ui, /const customBodyId =/)
  assert.match(ui, /"aria-controls": customBodyId/)
  assert.match(ui, /id: customBodyId/)
  assert.match(ui, /aria-live.*polite/)
  assert.match(ui, /dsh-reasoning-status--saving/)
  assert.match(ui, /远端已更新/)
  assert.match(ui, /dsh-reasoning-remote-status/)
  assert.match(ui, /role: "status"/)
  assert.match(ui, /"aria-live": "polite"/)
  assert.match(ui, /saveInFlightRef/)
  assert.match(ui, /重新载入/)
  assert.match(ui, /reloadDraft/)
  assert.match(ui, /draftSignature/)
  assert.match(ui, /controller\.save\(route, model\.id, draftToSave\.mode, draftToSave\.efforts, savingRevision\)/)
  assert.match(styles, /\.dsh-reasoning-model\{[^}]*border-radius:8px/)
  assert.match(styles, /\.dsh-reasoning-model__footer\{[^}]*justify-content:flex-end/)
  assert.match(styles, /\.dsh-reasoning-model__footer\{[^}]*flex-wrap:wrap/)
  assert.match(styles, /\.dsh-reasoning-levels__options\{[^}]*flex-wrap:wrap/)
  assert.match(styles, /\.dsh-reasoning-custom__toggle\{[^}]*width:100%/)
  assert.match(styles, /\.dsh-reasoning-model__header\{[^}]*min-width:0/)
  assert.match(styles, /\.dsh-reasoning-status\{[^}]*min-width:0/)
  assert.match(styles, /\.dsh-reasoning-status--saving\{/)
  assert.match(styles, /\.dsh-reasoning-reload\{/)
})

test('import rows use compact two-line structure and status badges', async () => {
  const importer = await readFile(new URL('src/ui/CCSwitchImportSection.mjs', root), 'utf8')
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  assert.match(importer, /dsh-ccswitch-import__content/)
  assert.match(importer, /dsh-ccswitch-import__primary-line/)
  assert.match(importer, /dsh-ccswitch-import__meta-line/)
  assert.match(importer, /dsh-ccswitch-import__badge--\$\{safe\}/)
  assert.doesNotMatch(importer, /dsh-ccswitch-import__meta"/)
  assert.doesNotMatch(importer, /dsh-ccswitch-import__status/)
  assert.match(styles, /\.dsh-ccswitch-import__badge\{[^}]*border-radius:999px/)
  assert.match(styles, /\.dsh-ccswitch-import__badge--new/)
  assert.match(styles, /\.dsh-ccswitch-import__badge--blocked/)
})

test('reasoning pills and save status use unified badge styling', async () => {
  const ui = await readFile(new URL('src/ui/ReasoningSettingsSection.mjs', root), 'utf8')
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  assert.match(ui, /dsh-reasoning-level--active/)
  assert.match(styles, /\.dsh-reasoning-level--active\{[^}]*--dsw-alias-brand-primary/)
  assert.match(styles, /\.dsh-reasoning-status\{[^}]*border-radius:999px/)
})

test('importer keeps the settings content usable on narrow screens', async () => {
  const styles = await readFile(new URL('src/client/styles.mjs', root), 'utf8')
  assert.match(styles, /\[role='dialog'\]:has\(\.dsh-ccswitch-import\)>nav\{[^}]*width:56px/)
  assert.match(styles, /\[role='dialog'\]:has\(\.dsh-ccswitch-import\)>nav button\{[^}]*width:40px/)
  assert.match(styles, /\[role='dialog'\]:has\(\.dsh-ccswitch-import\)>nav button>span\{[^}]*clip:rect/)
  assert.match(styles, /\.dsh-ccswitch-import__row\{[^}]*min-width:0/)
  assert.match(styles, /\.dsh-ccswitch-import__content\{[^}]*min-width:0/)
})
